### ISSUE TITLE
Running `pnpm prod`, as stated in README.md, emits error

### ISSUE THREAD

**Issue by naturalprogrammer** [phonzammi/vike-hono-example#1]
Running `pnpm prod`, as stated in README.md, emits error
```
'prod' is not recognized as an internal or external command,
operable program or batch file.
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "prod" not found
```

My terminal: Windows Powershell

**Comment by phonzammi** [comment]
Thank you @naturalprogrammer 
I've updated the command in `package.json` and the README.
I hope that helps.
